language: bash

env:
  global:
  - IMAGE_NAME=spark-custom-addons

matrix:
  include:
  # Debian builds
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian

  # Alpine builds
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=3.1.0
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.11
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=2.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.5
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.6
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - SCALA_VERSION=2.12
    - HADOOP_VERSION=2.7.3
    - PYTHON_VERSION=3.7
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine

script:
- shellcheck push-images.sh
- HIVE_TAG_SUFFIX="$(if [ "${WITH_HIVE}" = "true" ]; then echo _hive; fi)"
- PYSPARK_TAG_SUFFIX="$(if [ "${WITH_PYSPARK}" = "true" ]; then echo _pyspark; fi)"
- TAG_NAME="${SPARK_VERSION}_scala-${SCALA_VERSION}_hadoop-${HADOOP_VERSION}_python-${PYTHON_VERSION}${HIVE_TAG_SUFFIX}${PYSPARK_TAG_SUFFIX}_${DIST}"
- |-
  docker build ${DIST}/ -t "guangie88/${IMAGE_NAME}:${TAG_NAME}" \
    --build-arg "SPARK_VERSION=${SPARK_VERSION}" \
    --build-arg "SCALA_VERSION=${SCALA_VERSION}" \
    --build-arg "HADOOP_VERSION=${HADOOP_VERSION}" \
    --build-arg "PYTHON_VERSION=${PYTHON_VERSION}" \
    --build-arg "AWS_JAVA_SDK_VERSION=${AWS_JAVA_SDK_VERSION}" \
    --build-arg "HIVE_TAG_SUFFIX=${HIVE_TAG_SUFFIX}" \
    --build-arg "PYSPARK_TAG_SUFFIX=${PYSPARK_TAG_SUFFIX}" \
    ;

deploy:
  provider: script
  script: bash push-images.sh
  on:
    branch: master

branches:
  only:
  - master
