version: 2

#
# Build step
#

shared_build: &shared_build
  environment:
    IMAGE_NAME: guangie88/spark-custom-addons
    FROM_DOCKER_IMAGE: guangie88/spark-custom

  steps:
  - checkout
  - setup_remote_docker:
      docker_layer_caching: true
  - run:
      name: Get additional values for checking cache
      command: |
        DOCKER_VERSION=$(docker --version)
        echo ${DOCKER_VERSION} >> /tmp/cache-hash

        FROM_DOCKER_TAG="${SPARK_VERSION}_hadoop-${HADOOP_VERSION}${HIVE_TAG_SUFFIX}${PYSPARK_TAG_SUFFIX}"
        DOCKER_BUILD_IMAGE_DIGEST="$(docker pull ${FROM_DOCKER_IMAGE}:${FROM_DOCKER_TAG} | grep 'Digest:' | sed -E 's/Digest: (.+)/\1/')"
        echo ${DOCKER_BUILD_IMAGE_DIGEST} >> /tmp/cache-hash

        DOCKERFILE_HASH=$(cat Dockerfile-${DIST} | md5sum | cut -d' ' -f1)
        echo ${DOCKERFILE_HASH} >> /tmp/cache-hash

        echo ${SPARK_VERSION} >> /tmp/cache-hash
        echo ${HADOOP_VERSION} >> /tmp/cache-hash
        echo ${WITH_HIVE} >> /tmp/cache-hash
        echo ${WITH_PYSPARK} >> /tmp/cache-hash

        echo ${DIST} >> /tmp/cache-hash

        cat /tmp/cache-hash

  - run:
      name: Create artifacts directory
      command: mkdir -p /tmp/artifacts
  - run:
      name: Build Docker image and save tar as artifact
      command: |
        HIVE_TAG_SUFFIX=$(if [ "${WITH_HIVE}" = "true" ]; then echo _with-hive; fi)
        PYSPARK_TAG_SUFFIX=$(if [ "${WITH_PYSPARK}" = "true" ]; then echo _with-pyspark; fi)
        FROM_DOCKER_TAG="${SPARK_VERSION}_hadoop-${HADOOP_VERSION}${HIVE_TAG_SUFFIX}${PYSPARK_TAG_SUFFIX}"

        docker build . -t ${IMAGE_NAME}:ref \
          --build-arg FROM_DOCKER_TAG=${FROM_DOCKER_TAG}

        docker tag ${IMAGE_NAME}:ref ${IMAGE_NAME}:${FROM_DOCKER_TAG}
        docker save ${IMAGE_NAME}:${FROM_DOCKER_TAG} > /tmp/artifacts/docker-image.tar
  - persist_to_workspace:
      root: /tmp/artifacts
      paths:
      - docker-image.tar

jobs:
  build:
    
    docker:
    - image: circleci/python:3-stretch
      environment:
        SPARK_VERSION: 2.4.0
        HADOOP_VERSION: 3.1.0
        WITH_HIVE: "true"
        WITH_PYSPARK: "true"
      
    

  publish:
    docker:
    - image: circleci/python:3-stretch

    steps:
    - attach_workspace:
        at: /tmp/artifacts
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Log in to Docker registry
        command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run:
        name: Load from previous Docker build and push image into Docker
        command: |
          IMAGE_WITH_TAG_NAME=$(docker load < /tmp/artifacts/docker-image.tar | sed -E 's/Loaded image: (.+)/\1/')
          docker push ${IMAGE_WITH_TAG_NAME}

workflows:
  version: 2
  build_and_publish:
    jobs:
    - build
    - publish:
        requires:
          - build
        filters:
          branches:
            only:
            - master
